endpoint_url = "https://up.chat.sum7.eu"
jwt_secret = "CHANGEME"

[log]
level = 40
timestamp = false

[webserver]
listen = ":8080"
access_log = false
webroot = ""

# if ACME / Let's Encrypt used, uncomment listen
[webserver.acme]
enable = false
domains = ["example1.com", "example2.com"]
cache = "/var/www/.cache"


[xmpp]
address =  "[::1]:5347"
jid     =  "up.chat.sum7.eu"
secret  =  "CHANGEME"
